version: "3"
services:
  httpd-01:
    image: httpd
    container_name: httpd-01
    environment:
      - VIRTUAL_HOST=httpd01.localhost
    volumes:
      - ./public-html-01/:/usr/local/apache2/htdocs/

  httpd-02:
    image: httpd
    container_name: httpd-02
    environment:
      - VIRTUAL_HOST=httpd02.localhost
    volumes:
      - ./public-html-02/:/usr/local/apache2/htdocs/

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: "5m" # 明示的に文字列型で記述しないとエラーになる
        max-file: "10" # 明示的に文字列型で記述しないとエラーになる
